### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by primetoxinz** [primetoxinz/Caravans#3]
- [ ] Hostile Caravans
- [ ] Custom Entity Trade Data
- [ ] Caravans attack if attacked
- [ ] Entity -> Item Trades
